# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/selhua/Documents/cmpt414-vid

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/selhua/Documents/cmpt414-vid

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/selhua/Documents/cmpt414-vid/CMakeFiles /home/selhua/Documents/cmpt414-vid/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/selhua/Documents/cmpt414-vid/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named DisplayImage

# Build rule for target.
DisplayImage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 DisplayImage
.PHONY : DisplayImage

# fast build rule for target.
DisplayImage/fast:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/build
.PHONY : DisplayImage/fast

SIFT.o: SIFT.cpp.o
.PHONY : SIFT.o

# target to build an object file
SIFT.cpp.o:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/SIFT.cpp.o
.PHONY : SIFT.cpp.o

SIFT.i: SIFT.cpp.i
.PHONY : SIFT.i

# target to preprocess a source file
SIFT.cpp.i:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/SIFT.cpp.i
.PHONY : SIFT.cpp.i

SIFT.s: SIFT.cpp.s
.PHONY : SIFT.s

# target to generate assembly for a file
SIFT.cpp.s:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/SIFT.cpp.s
.PHONY : SIFT.cpp.s

descriptor.o: descriptor.cpp.o
.PHONY : descriptor.o

# target to build an object file
descriptor.cpp.o:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/descriptor.cpp.o
.PHONY : descriptor.cpp.o

descriptor.i: descriptor.cpp.i
.PHONY : descriptor.i

# target to preprocess a source file
descriptor.cpp.i:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/descriptor.cpp.i
.PHONY : descriptor.cpp.i

descriptor.s: descriptor.cpp.s
.PHONY : descriptor.s

# target to generate assembly for a file
descriptor.cpp.s:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/descriptor.cpp.s
.PHONY : descriptor.cpp.s

orientation.o: orientation.cpp.o
.PHONY : orientation.o

# target to build an object file
orientation.cpp.o:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/orientation.cpp.o
.PHONY : orientation.cpp.o

orientation.i: orientation.cpp.i
.PHONY : orientation.i

# target to preprocess a source file
orientation.cpp.i:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/orientation.cpp.i
.PHONY : orientation.cpp.i

orientation.s: orientation.cpp.s
.PHONY : orientation.s

# target to generate assembly for a file
orientation.cpp.s:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/orientation.cpp.s
.PHONY : orientation.cpp.s

scale.o: scale.cpp.o
.PHONY : scale.o

# target to build an object file
scale.cpp.o:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/scale.cpp.o
.PHONY : scale.cpp.o

scale.i: scale.cpp.i
.PHONY : scale.i

# target to preprocess a source file
scale.cpp.i:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/scale.cpp.i
.PHONY : scale.cpp.i

scale.s: scale.cpp.s
.PHONY : scale.s

# target to generate assembly for a file
scale.cpp.s:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/scale.cpp.s
.PHONY : scale.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... DisplayImage"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... SIFT.o"
	@echo "... SIFT.i"
	@echo "... SIFT.s"
	@echo "... descriptor.o"
	@echo "... descriptor.i"
	@echo "... descriptor.s"
	@echo "... orientation.o"
	@echo "... orientation.i"
	@echo "... orientation.s"
	@echo "... scale.o"
	@echo "... scale.i"
	@echo "... scale.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

